language: node_js
node_js:
  - lts/*
install:
  - npm ci # yarn install
script:
  - npm run docs:build # yarn docs:build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vitepress/dist
  github_token: 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 # A token generated on GitHub allowing Travis to push code on you repository. Set in the Travis settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master